version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: trafficpay-api-gateway
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - AUTH_SERVICE_URL=http://auth-service:5001
      - FINES_SERVICE_URL=http://fines-service:5002
      - PAYMENTS_SERVICE_URL=http://payments-service:5003
    depends_on:
      - auth-service
      - fines-service
      - payments-service

  auth-service:
    build: ./auth-service
    container_name: trafficpay-auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/traffic_pay
      - JWT_SECRET=supersecretjwtkey12345
      - JWT_EXPIRES=24h
    depends_on:
      - mongodb

  fines-service:
    build: ./fines-service
    container_name: trafficpay-fines-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/traffic_pay
      - JWT_SECRET=supersecretjwtkey12345
    depends_on:
      - mongodb

  payments-service:
    build: ./payments-service
    container_name: trafficpay-payments-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/traffic_pay
      - JWT_SECRET=supersecretjwtkey12345
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: trafficpay-mongodb
    ports:
      - "27017:27017"

  driver-portal:
    build: ./driver-portal
    container_name: trafficpay-driver-portal
    ports:
      - "5173:80"
    depends_on:
      - api-gateway

  admin-portal:
    build: ./admin-portal
    container_name: trafficpay-admin-portal
    ports:
      - "5174:80"
    depends_on:
      - api-gateway
